<?xml version="1.0"?>
<!-- за вътрешен DTD пиша граматиката във файла-->
<!--дефинирам документа с неговите атрибути и елементи--> 
<!DOCTYPE shiporder[ 
<!ELEMENT shiporder (orderperson,shipto,item+)>
<!--имам елемент и елементно съдържание и под елемент item, който се среща повече пъти и за това слагам + -->
<!ATTLIST shiporder orderid CDATA #REQUIRED>
<!--декларирам атрибут, свързан с елемента shiporder и се задава име, тип и стойност, REQUIRED пиша, защото трябва да бъде зададена стойността-->
<!--дефинирам и другите елементи-->
<!ELEMENT orderperson (#PCDATA)>
<!ELEMENT shipto (name,address,city,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT item (title,note?,quantity,price)>
<!--за note слагам ?, защото се среща само веднъж-->
<!ELEMENT title (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<shiporder orderid="889923">
	<orderperson>John Smith</orderperson>
	<shipto>
		<name>Ola Nordmann</name>
		<address>Langgt 23</address>
		<city>4000 Stavenger</city>
		<country>Norway</country>
	</shipto>
	<item>
		<title>Empire Burlesque</title>
		<note>Special Edition</note>
		<quantity>1</quantity>
		<price>10.90</price>
	</item>
	<item>
		<title>Hide your heart</title>
		<quantity>1</quantity>
		<price>9.90</price>
	</item>
</shiporder>